name: food-classifier

channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.7
  - pip=19.0.3
  - pip:
    - numpy==1.19.2
    - pandas==1.1.3
    - tensorflow-cpu==2.4.1
    - flask==1.1.2
    - pillow==8.0.1

