name: polyaxon-assignment7

channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.7
  - pip=19.0.3
 # - pip=20.2.4
  - pip:
    - polyaxon_client==0.5.6
    - numpy==1.19.2
    - pandas==1.1.3
    - tensorflow==2.4.0
    - flask==1.1.2
    - waitress==1.4.4
    - pillow==8.0.1

# Feel free to change the version of any package
